"""
Planner Agent
=============
Deconstructs natural language claims into categorized epistemological plans,
extracts core semantic concepts, and generates 3 strictly separated,
operator-injected queries (preventing query concatenation).
Equipped with temporal and entertainment heuristics to avoid stale Wikipedia queries.
"""

import json
import logging
import re
from typing import Any
from pydantic import BaseModel, Field

from .llm_client import call_llm, clean_llm_json
from .search_tools import POP_CULTURE_KEYWORDS, select_engines

logger = logging.getLogger(__name__)

TEMPORAL_MARKERS = [
    "right now", "today", "current episode", "latest", "recent", "now",
    "yesterday", "this week", "live", "ongoing", "currently"
]

ENTERTAINMENT_MARKERS = [
    "serial", "episode", "season", "cast", "plot", "character", "movie",
    "cinema", "tv show", "sun tv", "star plus", "actor", "actress", "who is helping"
]


class Plan(BaseModel):
    """Execution plan generated by the Planner Agent."""

    claim: str
    claim_type: str
    core_concepts: list[str] = Field(
        description="Key conceptual tokens/phrases for semantic relevance gating",
        default_factory=list,
    )
    queries: list[str] = Field(
        description="Exactly 3 distinct, unconcatenated search queries",
        min_length=1,
        max_length=3,
    )
    target_surfaces: list[str] = Field(default_factory=lambda: ["google", "google_scholar"])
    is_temporal: bool = False


def classify_claim_type_heuristic(claim: str) -> str:
    """Fast keyword fallback for claim categorization."""
    c = claim.lower()

    if any(k in c for k in POP_CULTURE_KEYWORDS) or any(k in c for k in ENTERTAINMENT_MARKERS):
        return "entertainment_media"

    if any(k in c for k in [
        "creatine", "supplement", "dose", "protein", "health", "cancer", "vaccine",
        "disease", "clinical", "optical", "scientific", "physics", "chemical", "celsius",
        "pressure", "freez", "boil", "temperature", "hair loss", "dna", "cell", "vacuum",
        "decay", "void", "cosmology", "quantum", "gravity"
    ]):
        return "scientific"

    if any(k in c for k in [
        "launched", "released", "announced", "2024", "2025", "2026", "yesterday",
        "last month", "recently", "sora", "openai", "acquisition", "died", "resigned",
        "war", "election", "bose", "crash"
    ] + TEMPORAL_MARKERS):
        return "temporal_news"

    if any(k in c for k in ["pricing", "cost", "features", "saas", "api", "subscription"]):
        return "commercial_saas"

    return "general_factoid"


def extract_core_terms_heuristic(claim: str) -> list[str]:
    """Extract significant keywords from a claim for relevance guarding."""
    stop_words = {
        "is", "the", "will", "us", "what", "happened", "when", "it", "touch", "our",
        "a", "an", "and", "or", "in", "on", "at", "to", "for", "of", "with", "by",
        "that", "this", "does", "do", "did", "can", "could", "would", "should", "are"
    }
    words = re.findall(r"\b[a-zA-Z]{3,}\b", claim.lower())
    terms = [w for w in words if w not in stop_words]
    return terms[:6] or [claim[:30]]


class PlannerAgent:
    """
    Principal Search Planner that translates a natural language claim into
    3 isolated search operator queries and an epistemological execution plan.
    """

    def plan(self, claim: str) -> Plan:
        """
        Deconstruct claim and return a validated Plan.
        Guarantees that queries are 3 separate bounded strings and never concatenated.
        """
        c_lower = claim.lower()
        is_temporal = any(m in c_lower for m in TEMPORAL_MARKERS)
        is_entertainment = any(m in c_lower for m in ENTERTAINMENT_MARKERS)

        heuristic_type = "temporal_news" if (is_temporal or is_entertainment) else classify_claim_type_heuristic(claim)
        heuristic_terms = extract_core_terms_heuristic(claim)

        temporal_instruction = ""
        if is_temporal or is_entertainment:
            temporal_instruction = f"""
SPECIAL ENTERTAINMENT & REGIONAL RECENCY RULES:
The query asks about daily TV serials, soap operas, or ongoing entertainment plots:
- NEVER use corporate streaming portal site operators like site:sunnetwork.in, site:hotstar.com, or site:wikipedia.org (they only host static corporate landing pages or tables, not daily plot summaries).
- Query 1: Use recap keywords: "{claim} written update today episode recap"
- Query 2: Target entertainment portals: "{claim} plot summary latest episode"
- Query 3: Search character dynamics: "{claim} cast characters helping"
"""

        prompt = f"""You are the Planner Agent in an Epistemic Fact-Verification system.

Analyze this claim and create a high-precision search plan.

CLAIM: "{claim}"
{temporal_instruction}

TASK:
1. Classify the claim type ("scientific" | "temporal_news" | "commercial_saas" | "general_factoid").
2. Identify 3 to 5 core conceptual terms or entities crucial for topic relevance.
3. Generate EXACTLY 3 distinct, non-overlapping Google search queries:
   - Query 1 (Primary Authority / Direct Entity / Recap): Targeted terminology, official record, or episode recap.
   - Query 2 (Consensus / Synthesis / Recap): Consensus phrasing or episode/development recap.
   - Query 3 (Counter-Hypothesis / Myth Origin): Origin of misconception, debunking, or character dynamics.

IMPORTANT CONSTRAINTS:
- Do NOT output a single concatenated query.
- Each query must be a standalone search string of at most 12 words.
- Return ONLY valid JSON with this exact schema:

{{
  "claim_type": "scientific | temporal_news | commercial_saas | general_factoid",
  "core_concepts": ["concept1", "concept2", "concept3"],
  "queries": [
    "query 1 string",
    "query 2 string",
    "query 3 string"
  ]
}}"""

        try:
            response = call_llm(prompt, response_mime_type="application/json")
            data = clean_llm_json(response)
            if not isinstance(data, dict):
                data = {}

            claim_type = str(data.get("claim_type", heuristic_type)).lower()
            is_pop_culture = any(k in c_lower for k in POP_CULTURE_KEYWORDS)
            if is_pop_culture or is_entertainment:
                claim_type = "entertainment_media"
            elif is_temporal:
                claim_type = "temporal_news"

            raw_concepts = data.get("core_concepts", [])
            core_concepts = [str(c).strip().lower() for c in raw_concepts if str(c).strip()]
            if not core_concepts:
                core_concepts = heuristic_terms

            raw_queries = data.get("queries", [])
            sanitized_queries: list[str] = []

            # Handle list of queries
            if isinstance(raw_queries, list):
                for q in raw_queries:
                    q_str = str(q).strip().replace("\n", " ")
                    # Guard against corporate portal locks on real-time queries
                    if is_temporal or is_entertainment or is_pop_culture:
                        for blocked_op in ("site:wikipedia.org", "site:sunnetwork.in", "site:hotstar.com", "site:sunnxt.net"):
                            if blocked_op in q_str:
                                q_str = q_str.replace(blocked_op, "").strip()

                    # Guard against query concatenation bug
                    if len(q_str) > 130 and "site:" in q_str:
                        parts = re.split(r"(?<=[a-zA-Z0-9])\s+(?=site:)", q_str)
                        for p in parts:
                            if p.strip() and len(sanitized_queries) < 3:
                                sanitized_queries.append(p.strip())
                    elif q_str:
                        sanitized_queries.append(q_str)

            valid_queries = []
            for q in sanitized_queries:
                if q not in valid_queries:
                    valid_queries.append(q)
                if len(valid_queries) == 3:
                    break

            if not valid_queries:
                if is_temporal or is_entertainment or is_pop_culture:
                    valid_queries = [
                        f"{' '.join(core_concepts[:3])} latest episode recap",
                        f"{' '.join(core_concepts[:3])} character cast details",
                        f"{' '.join(core_concepts[:3])} news update",
                    ]
                else:
                    valid_queries = [
                        f"{' '.join(core_concepts[:3])} official analysis",
                        f"{' '.join(core_concepts[:3])} scientific consensus",
                        f"{' '.join(core_concepts[:3])} debunked myth origin",
                    ]

            # Determine target surfaces (strictly suppress scholar for pop culture/media)
            if is_pop_culture or is_entertainment or claim_type in ("entertainment_media", "temporal_news", "commercial_saas"):
                surfaces = ["google", "google_news"]
            elif claim_type == "scientific":
                surfaces = ["google", "google_scholar"]
            else:
                surfaces = select_engines(claim)

            return Plan(
                claim=claim,
                claim_type=claim_type,
                core_concepts=core_concepts,
                queries=valid_queries[:3],
                target_surfaces=surfaces,
                is_temporal=(is_temporal or is_entertainment),
            )

        except Exception as exc:
            logger.warning("PlannerAgent encountered error (%s), using deterministic plan", exc)
            fallback_concepts = heuristic_terms
            if is_temporal or is_entertainment:
                fallback_queries = [
                    f"{' '.join(fallback_concepts[:3])} today episode recap",
                    f"{' '.join(fallback_concepts[:3])} character cast details",
                    f"{' '.join(fallback_concepts[:3])} news update",
                ]
                surfaces = ["google", "google_news"]
            else:
                fallback_queries = [
                    f"{' '.join(fallback_concepts[:3])} primary review",
                    f"{' '.join(fallback_concepts[:3])} scientific consensus",
                    f"{' '.join(fallback_concepts[:3])} debunked origin",
                ]
                surfaces = ["google", "google_scholar"] if heuristic_type == "scientific" else ["google", "google_news"]

            return Plan(
                claim=claim,
                claim_type=heuristic_type,
                core_concepts=fallback_concepts,
                queries=fallback_queries,
                target_surfaces=surfaces,
                is_temporal=(is_temporal or is_entertainment),
            )
