"""
Planner Agent
=============
Deconstructs natural language claims into categorized epistemological plans,
extracts core semantic concepts, and generates 3 strictly separated,
operator-injected queries (preventing query concatenation).
"""

import json
import logging
import re
from typing import Any
from pydantic import BaseModel, Field

from .llm_client import call_llm

logger = logging.getLogger(__name__)


class Plan(BaseModel):
    """Execution plan generated by the Planner Agent."""

    claim: str
    claim_type: str
    core_concepts: list[str] = Field(
        description="Key conceptual tokens/phrases for semantic relevance gating",
        default_factory=list,
    )
    queries: list[str] = Field(
        description="Exactly 3 distinct, unconcatenated search queries",
        min_length=1,
        max_length=3,
    )
    target_surfaces: list[str] = Field(default_factory=lambda: ["google", "google_scholar"])


def classify_claim_type_heuristic(claim: str) -> str:
    """Fast keyword fallback for claim categorization."""
    c = claim.lower()
    if any(k in c for k in [
        "creatine", "supplement", "dose", "protein", "health", "cancer", "vaccine",
        "disease", "clinical", "optical", "scientific", "physics", "chemical", "celsius",
        "pressure", "freez", "boil", "temperature", "hair loss", "dna", "cell", "vacuum",
        "decay", "void", "cosmology", "quantum", "gravity"
    ]):
        return "scientific"

    if any(k in c for k in [
        "launched", "released", "announced", "2024", "2025", "2026", "yesterday",
        "last month", "recently", "sora", "openai", "acquisition", "died", "resigned",
        "war", "election", "bose", "crash"
    ]):
        return "temporal_news"

    if any(k in c for k in ["pricing", "cost", "features", "saas", "api", "subscription"]):
        return "commercial_saas"

    return "general_factoid"


def extract_core_terms_heuristic(claim: str) -> list[str]:
    """Extract significant keywords from a claim for relevance guarding."""
    stop_words = {
        "is", "the", "will", "us", "what", "happened", "when", "it", "touch", "our",
        "a", "an", "and", "or", "in", "on", "at", "to", "for", "of", "with", "by",
        "that", "this", "does", "do", "did", "can", "could", "would", "should", "are"
    }
    words = re.findall(r"\b[a-zA-Z]{3,}\b", claim.lower())
    terms = [w for w in words if w not in stop_words]
    return terms[:6] or [claim[:30]]


class PlannerAgent:
    """
    Principal Search Planner that translates a natural language claim into
    3 isolated search operator queries and an epistemological execution plan.
    """

    def plan(self, claim: str) -> Plan:
        """
        Deconstruct claim and return a validated Plan.
        Guarantees that queries are 3 separate bounded strings and never concatenated.
        """
        heuristic_type = classify_claim_type_heuristic(claim)
        heuristic_terms = extract_core_terms_heuristic(claim)

        prompt = f"""You are the Planner Agent in an Epistemic Fact-Verification system.

Analyze this claim and create a high-precision search plan.

CLAIM: "{claim}"

TASK:
1. Classify the claim type ("scientific" | "temporal_news" | "commercial_saas" | "general_factoid").
2. Identify 3 to 5 core conceptual terms or entities crucial for topic relevance.
3. Generate EXACTLY 3 distinct, non-overlapping Google search queries:
   - Query 1 (Academic / Primary Authority): Targeted terminology, site operator or official release.
   - Query 2 (Consensus / Meta-Analysis): Consensus phrasing or systematic synthesis.
   - Query 3 (Counter-Hypothesis / Myth Origin): Origin of misconception, debunking, or counter-evidence.

IMPORTANT CONSTRAINTS:
- Do NOT output a single concatenated query.
- Each query must be a standalone search string of at most 12 words.
- Return ONLY valid JSON with this exact schema:

{{
  "claim_type": "scientific | temporal_news | commercial_saas | general_factoid",
  "core_concepts": ["concept1", "concept2", "concept3"],
  "queries": [
    "query 1 string",
    "query 2 string",
    "query 3 string"
  ]
}}"""

        try:
            response = call_llm(prompt, response_mime_type="application/json")
            cleaned = response.strip()
            if cleaned.startswith("```"):
                cleaned = cleaned.split("\n", 1)[1]
            if cleaned.endswith("```"):
                cleaned = cleaned.rsplit("```", 1)[0]
            data = json.loads(cleaned.strip())

            claim_type = str(data.get("claim_type", heuristic_type)).lower()
            raw_concepts = data.get("core_concepts", [])
            core_concepts = [str(c).strip().lower() for c in raw_concepts if str(c).strip()]
            if not core_concepts:
                core_concepts = heuristic_terms

            raw_queries = data.get("queries", [])
            sanitized_queries: list[str] = []

            # Handle list of queries
            if isinstance(raw_queries, list):
                for q in raw_queries:
                    q_str = str(q).strip().replace("\n", " ")
                    # Guard against query concatenation bug: if query is excessively long, truncate or split
                    if len(q_str) > 130 and "site:" in q_str:
                        # Extract first coherent query chunk
                        parts = re.split(r"(?<=[a-zA-Z0-9])\s+(?=site:)", q_str)
                        for p in parts:
                            if p.strip() and len(sanitized_queries) < 3:
                                sanitized_queries.append(p.strip())
                    elif q_str:
                        sanitized_queries.append(q_str)

            # Ensure we have at least 1 and at most 3 distinct queries
            valid_queries = []
            for q in sanitized_queries:
                if q not in valid_queries:
                    valid_queries.append(q)
                if len(valid_queries) == 3:
                    break

            if not valid_queries:
                valid_queries = [
                    f"{' '.join(core_concepts[:3])} official analysis",
                    f"{' '.join(core_concepts[:3])} scientific consensus",
                    f"{' '.join(core_concepts[:3])} debunked myth origin",
                ]

            # Determine target surfaces based on claim type
            surfaces = ["google", "google_scholar"] if claim_type == "scientific" else ["google", "google_news"]

            return Plan(
                claim=claim,
                claim_type=claim_type,
                core_concepts=core_concepts,
                queries=valid_queries[:3],
                target_surfaces=surfaces,
            )

        except Exception as exc:
            logger.warning("PlannerAgent encountered error (%s), using deterministic plan", exc)
            fallback_concepts = heuristic_terms
            fallback_queries = [
                f"{' '.join(fallback_concepts[:3])} primary review",
                f"{' '.join(fallback_concepts[:3])} scientific consensus",
                f"{' '.join(fallback_concepts[:3])} debunked origin",
            ]
            surfaces = ["google", "google_scholar"] if heuristic_type == "scientific" else ["google", "google_news"]
            return Plan(
                claim=claim,
                claim_type=heuristic_type,
                core_concepts=fallback_concepts,
                queries=fallback_queries,
                target_surfaces=surfaces,
            )
